# Units for pretty printing status
PRICE_CENTS = ' ¢/kWh'
PRICE_DOLLARS = ' $/kWh'
WATTS = ' W'
VOLTS = ' V'
AMPS = ' A'
KILOWATTS = ' kW'
SECONDS = ' seconds'
MINUTES = ' minutes'
HOURS = ' hours'
PERCENT = '%'
